### ISSUE TITLE
Solution for Cyber Initiative no longer valid

### ISSUE THREAD

**Issue by FalcoGer** [Yukinoshita-Yukino/while-true-learn-gold-solutions#1]
They changed Cyber Initiative's output block counts. And the solution in this repository doesn't work anymore.

**Comment by Yukinoshita-Yukino** [comment]
I'm no longer playing this game.
If anyone has new solution suits the latest version, PR is welcomed.

**Comment by tenshilove** [comment]
This link contains a solution for Cyber Initiative that worked for me: https://www.youtube.com/watch?v=SPERA__yv7E

**Comment by matthew-mcmahon** [comment]
> I'm no longer playing this game. If anyone has new solution suits the latest version, PR is welcomed.

PR: https://github.com/Yukinoshita-Yukino/while-true-learn-gold-solutions/pull/4

**Comment by Jagofalltrds** [comment]
![while True_ learn() 12_4_2021 12_51_54 PM](https://user-images.githubusercontent.com/95545067/144721325-185d21f6-be69-41e3-b9b2-3d1585b064fe.png)
![while True_ learn() 12_4_2021 12_51_45 PM](https://user-images.githubusercontent.com/95545067/144721326-b1d2f47c-9d5c-42d1-8e91-89ad2f64bb94.png)

Solved with 6 nodes Gold metal

**Comment by Jagofalltrds** [comment]
> > I'm no longer playing this game. If anyone has new solution suits the latest version, PR is welcomed.
> 
> PR: #4

I got you. Look above

**Comment by Yukinoshita-Yukino** [comment]
Should be updated by 
https://github.com/Yukinoshita-Yukino/while-true-learn-gold-solutions/pull/4

**Comment by vxtexcoder** [comment]
![image](https://github.com/user-attachments/assets/59c54bf2-9317-4019-9061-ec688790a9f8)

This is the 2025 updated version of it.
