### ISSUE TITLE
Sollution Cyber Initiative invalid

### ISSUE THREAD

**Issue by dukedagmor** [Yukinoshita-Yukino/while-true-learn-gold-solutions#11]
PR https://github.com/Yukinoshita-Yukino/while-true-learn-gold-solutions/pull/4 does not use the solution provided in ISSUE https://github.com/Yukinoshita-Yukino/while-true-learn-gold-solutions/issues/1.

The solution provided in PR https://github.com/Yukinoshita-Yukino/while-true-learn-gold-solutions/pull/4 is false.
The solution provided in ISSUE https://github.com/Yukinoshita-Yukino/while-true-learn-gold-solutions/issues/1 is correct => https://github.com/Yukinoshita-Yukino/while-true-learn-gold-solutions/issues/1#issuecomment-986076454

**Comment by matthew-mcmahon** [comment]
you might be using an old version of the game (this mission's objective was changed), I just checked with the current version and #4 is still valid for gold.
