### ISSUE TITLE
Solution for crowd control no longer works

### ISSUE THREAD

**Issue by blkarcher77** [Yukinoshita-Yukino/while-true-learn-gold-solutions#3]
In the image, it uses 8 nodes, while gold now requires a max of 6 nodes.

**Comment by blkarcher77** [comment]
![Solution](https://user-images.githubusercontent.com/49884918/144548296-ed21dbb6-6b04-4f82-9dc9-676b4a6bce65.png)

So here is an updated solution, but it's kind of weird, because I ran it multiple times. The first time, it failed, but barely. The second time, it finished with a gold. The next three times, it finished with bronze.

If someone has a better solution, please say so

**Comment by Yukinoshita-Yukino** [comment]
I'm no longer playing this game.
If anyone has new solution suits the latest version, PR is welcomed.

**Comment by ulrikbrondsted** [comment]
> So here is an updated solution, but it's kind of weird, because I ran it multiple times. **The first time, it failed, but barely. The second time, it finished with a gold. The next three times, it finished with bronze.**

How do you get different results running with the same setup? I always get the same result with a rerun, it seems like the elements are released in a predetermined order (or at least generated by the same random seed).

**Comment by celluj34** [comment]
I have a slightly different solution, which works reliably:

![image](https://user-images.githubusercontent.com/10264021/201547239-d9368b27-e402-4db8-b6b8-d5d83305755d.png)

I'll make a PR to update this image.

**Comment by Yukinoshita-Yukino** [comment]
Closed in #7
