### ISSUE TITLE
Meteorite Alarm Solution

### ISSUE THREAD

**Issue by filliravaz** [Yukinoshita-Yukino/while-true-learn-gold-solutions#5]
![Screenshot_9](https://user-images.githubusercontent.com/40716956/144856448-010a4809-75f7-4054-bc2b-b1139d98db0f.png)

**Comment by Yukinoshita-Yukino** [comment]
@vaio2005 Pls create an PR if you want to update the current solution, thx!

**Comment by filliravaz** [comment]
Made the PR, sorry for the very long wait :) 
#6

**Comment by Yukinoshita-Yukino** [comment]
Close by #6

**Comment by Shadow-Hunt3r** [comment]
To shave 1 node the Input 3 can be connected directly to the 75% Perceptron
Result:
![image](https://github.com/user-attachments/assets/4c3963cf-cc9e-484d-91fb-702c790b8ab3)

Layout:
![image](https://github.com/user-attachments/assets/0b04f0f1-6a0b-4835-9faf-ae4ba7cb6847)
